name: message_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.1.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  flutter_screenutil: ^5.9.0
  firebase_database: ^10.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: SFUI
      fonts:
        - asset: assets/fonts/sf-ui-display-black-58646a6b80d5a.otf
          weight: 900
        - asset: assets/fonts/sf-ui-display-bold-58646a511e3d9.otf
          weight: 700
        - asset: assets/fonts/sf-ui-display-heavy-586470160b9e5.otf
          weight: 400
        - asset: assets/fonts/sf-ui-display-light-58646b33e0551.otf
          weight: 200
        - asset: assets/fonts/sf-ui-display-medium-58646be638f96.otf
          weight: 500
        - asset: assets/fonts/sf-ui-display-semibold-58646eddcae92.otf
          weight: 600
        - asset: assets/fonts/sf-ui-display-thin-58646e9b26e8b.otf
          weight: 100



